### ISSUE TITLE
Criar o Mapa

### ISSUE THREAD

**Issue by lapisdecor** [InterruptorPt/ate-onde-chega-cultura#11]
Era boa ideia um query que tivesse tudo para termos uma ideia do mapa.
A segunda fase seria contruir o mapa. Não sei se é para ser OpenStreetMaps ou outra coisa.

A malta do Flutter podia fazer também uma app com o mapa.

**Comment by lapisdecor** [comment]
Nota: as apps de flutter correm no Ubuntu.

**Comment by marado** [comment]
Ainda pode ser muito melhorado (mas sugiro issues específicos para cada sugestões de melhoria), mas o mapa já existe: ff0cb145bd144ad8e1e58ff6af327f8aaeb8d6c6 .
