### ISSUE TITLE
escolher um ícone para os monumentos

### ISSUE THREAD

**Issue by marado** [InterruptorPt/ate-onde-chega-cultura#17]
Em https://github.com/miukimiu/ate-onde-chega-cultura/pull/1 adiciona-se o suporte de monumentos para este projecto (tanto nos mapas separados como na aplicação flutter).

No entanto, em https://github.com/miukimiu/ate-onde-chega-cultura/pull/1/commits/6fecc010d770253eee79a0de5681b6e03ddd4dc1#diff-96ce2087d61aaa7bfb98313b870d8ecc57d63f2a1a381c6fda230f3f91259306R50 , estamos a usar para monumentos o mesmo ícone dos teatros, devíamos escolher um ícone diferente...

**Comment by hugopeixoto** [comment]
Que achas do "account_balance"?

https://github.com/google/material-design-icons/blob/master/src/action/account_balance/materialicons/24px.svg

**Comment by marado** [comment]
works for me!

**Comment by hugopeixoto** [comment]
o PR que linkaste não é neste repositório, é propositado?

**Comment by marado** [comment]
é continuação de um branch que foi criado noutro lado, mas posso...
*passam-se uns segundos*
Pronto, já tens o #33 :-)

**Comment by marado** [comment]
Closed with ba120548e542d83fd4a7496a5d71cf8d30a1739e .

**Comment by waldyrious** [comment]
> Closed with ba12054.

Estava precisamente a comentar que o PR#33 foi merged com o ícone sugerido acima (`account_balance`). :)
