### ISSUE TITLE
Copiar o ficheiro .gitignore para a pasta root do repositório?

### ISSUE THREAD

**Issue by lapisdecor** [InterruptorPt/ate-onde-chega-cultura#19]
A aplicação mobile tem um .gitignore que está fora do root do projecto, não sei se isto tem implicações visto que para abrir o projecto mobile abro a pasta correspondente, mas a documentação do github diz que o .gitignore deve estar no root.

No entanto, isto também põe um problema para quem desenvolve porque se abrimos o projecto a partir do seu root verdadeiro ficamos com o projecto mobile como subpasta o que pode não dar muito jeito por exemplo no android-studio.

Qual é a solução? Ter dois .gitignore?

**Comment by marado** [comment]
Da [documentação](https://git-scm.com/docs/gitignore) do `git`:
> Patterns read from a .gitignore file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the toplevel of the work tree) being overridden by those in lower level files down to the directory containing the file.
Quer isto dizer que um `.gitignore` pode viver numa subdirectoria sem estar um na raíz, ou pode haver mais do que um (um na raíz, um nas sub-directorias...).

Pelo que me parece não há nada no `.gitignore` existente que precise de ser global, por isso, se calhar, não há nada aqui para fazer?

**Comment by lapisdecor** [comment]
Optimo, tinha aqui um problema com uma pasta mas pelos vistos o problema era só meu, eu é que pensei que era do .gitignore . Podemos fechar isto.
