### ISSUE TITLE
Wikidata queries para outros espaços

### ISSUE THREAD

**Issue by aariops** [InterruptorPt/ate-onde-chega-cultura#2]
No seguimento do PR #1 do @marado, ir buscar as queries de Wikidata para os seguintes equipamentos culturais em Portugal:
-  [x] teatros
-  [x] cinemas
-  [x] museus
-  [x] recintos de espectáculo
-  [x] galerias de arte

O PR deve conter os ficheiros HTML.

**Comment by aariops** [comment]
o @pedrorio adicinou estes no #5

**Comment by marado** [comment]
E agora já temos teatros também graças ao #6 .

**Comment by lapisdecor** [comment]
se calhar há sobreposição por causa dos cine-teatros
são ao mesmo tempo teatro e cinema
tem que se ter isso em conta quando se fizer o mapa

outra coisa as galerias de arte presentes no wikidata são muito poucas, pelo menos com as queries que fiz

**Comment by marado** [comment]
Realmente o wikidata é (ainda?) uma fonte fraca para a lista de galerias de arte (só tem 1!, com a query actual).
@aariops achas que era de criar um issue especificamente para lidar com isso?

**Comment by aariops** [comment]
Vou fechar isto, então. Seguimos com issues mais granulares. Como este #16
