### ISSUE TITLE
tentar ter uma "página web única" para os vários mapas

### ISSUE THREAD

**Issue by marado** [InterruptorPt/ate-onde-chega-cultura#20]
Temos actualmente uma série de HTMLs estáticos em que a única coisa que muda é o texto do header e a query wikidata... Talvez usar uma ferramenta de templating ou algo do género fosse bom para manter só um .html em vez de vários "iguais".

**Comment by tcarreira** [comment]
achas que o #30 resolve isto?

**Comment by marado** [comment]
Yup!
