### ISSUE TITLE
Refatorizar queries e páginas html

### ISSUE THREAD

**Issue by tcarreira** [InterruptorPt/ate-onde-chega-cultura#39]
Agora que existe uma forma de mostrar tudo num só mapa, proponho o seguinte:

- [x] eliminar os vários ficheiros separados {bibliotecas,cinamas,galerias,...}.html
- [x] juntar as queries num único sítio (eg: 1 ficheiro por query?)
- [x] juntar o que está a ser feito em #28 e passar a consumir o conteúdo estático

O que te parece @marado ?

**Comment by marado** [comment]
gosto disto

**Comment by tcarreira** [comment]
Então vou pegar nisto.

**Comment by waldyrious** [comment]
> eliminar os vários ficheiros separados {bibliotecas,cinamas,galerias,...}.html

Acho que se podia deixar as páginas individuais no repositório, ainda que não linkadas da página inicial do site, para demonstrar o que se consegue apenas com o Wikidata e os mapas que ele gera automaticamente. WDYT?

**Comment by tcarreira** [comment]
> Acho que se podia deixar as páginas individuais no repositório, ainda que não linkadas da página inicial do site, para demonstrar o que se consegue apenas com o Wikidata e os mapas que ele gera automaticamente. WDYT?

O problema disto é a duplicação de dados. 
Posso deixar um e chamo-lhe `example-from-wikidata-iframe.html` por exemplo, mas acho que deixar todos é um ótimo passo para alguém editar coisas no sítio errado.

Parece-te bem?

Na verdade, com o #47 isto pode ser fechado.

**Comment by waldyrious** [comment]
Parece-me bem, boa ideia @tcarreira!
